name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  readjson:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: take value
        run: echo "MYJSON=$(cat myfile.json)" >> $GITHUB_ENV
  sdlc-run:
    needs: [ build, readjson ]
    uses: mevijays/action-sandbox/.github/workflows/reusable.yaml@main
    with:
       MULTIJSON: ${{ env.MYJSON }}
