name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  readjson:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      MYJSON: ${{ steps.getid.outputs.MYJSON }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: take value
        id: getid
        run: |-
          PATHFILE="myfile.json"
          echo "MYJSON=${PATHFILE}" >> GITHUB_OUTPUT
  sdlc-run:
    needs: [ build, readjson ]
    uses: mevijays/action-sandbox/.github/workflows/reusable.yaml@main
    with:
       MULTIJSON: ${{ needs.readjson.outputs.MYJSON }}
