name: reusable for call
permissions:
  contents: read
  id-token: write
on:
  workflow_call:
    inputs:
      MULTIJSON:
        type: string
        default: ''
jobs:
  getjob:
    runs-on: self-hosted
    name: getting value
    steps:
      - name: printing raw input
        run: echo "${{ inputs.MULTIJSON }}"
      - name: printing parsed value
        run: |-
          echo '${{ inputs.MULTIJSON }}' | jq .
      - name: random number
        run: |
          TAG=$(shuf -i 1000-9999 -n 1)
          echo "IMAGE_NAME=docker.io/images/mevijay/nginx:$TAG" >> $GITHUB_ENV
      - name: Notice this
        run: echo "##[notice] title=Image_name_is: ${{$IMAGE_NAME}}"
