name: reusable for call
permissions:
  contents: read
  id-token: write
on:
  workflow_call:
    inputs:
      MULTIJSON:
        type: string
        default: ''
jobs:
  getjob:
    runs-on: ubuntu-latest
    name: getting value
    steps:
      - name: printing raw input
        run: echo "${{ inputs.MULTIJSON }}"
      - name: printing parsed value
        run: |-
          echo '${{ inputs.MULTIJSON }}' | jq .
